# BUILD file in src directory

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    linkopts = ["-lstdc++fs"],
    visibility = ["//visibility:public"],
    deps = [],  # Add dependencies here
)
